# Generated by Django 3.2 on 2021-04-18 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=200)),
                ('firstParagraph', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
