# Generated by Django 3.2 on 2021-04-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(default='images/generic_user.png', upload_to='images/%Y/%m/%d/'),
        ),
    ]
