# Generated by Django 3.2 on 2021-04-15 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6921d16e-b58a-4fbc-a46c-f631cb49f580'), editable=False, primary_key=True, serialize=False),
        ),
    ]
