# Generated by Django 3.2 on 2021-04-17 22:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210415_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default='94304fb8-9525-451c-bcbb-8d10ea98ed1f', on_delete=django.db.models.deletion.CASCADE, to='news.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5fd92888-00fc-4406-bf97-4f3fa28f0329'), editable=False, primary_key=True, serialize=False),
        ),
    ]
