# Generated by Django 3.2 on 2021-04-18 00:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210417_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e346f98-f2ba-4c42-bedd-3053ec3cb9d7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
