version: '3.9'
services:
  db:
    image: postgres:12
    volumes:
      - "./data/db:/var/lib/postgres/data"
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    build: ./news_provider
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./news_provider:/code
    ports:
    - "80:80"
    depends_on:
      - db
    env_file:
      - .env
