# Generated by Django 3.2 on 2021-04-15 00:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9befcc7b-fd80-41b1-a981-f82756c3f389'), editable=False, primary_key=True, serialize=False),
        ),
    ]
