# Generated by Django 3.2 on 2021-04-15 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1aefdae-0717-4794-abb9-673b7408b8e4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
