# Generated by Django 3.2 on 2021-04-15 21:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1824f2e5-5ee6-4e60-b361-f9280deaa7da'), editable=False, primary_key=True, serialize=False),
        ),
    ]
